{
 "title": "dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "load1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "DISK I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "SELECT derivative(mean(\"read_bytes\"), 1s) FROM \"diskio\" WHERE \"name\"='mmcblk0' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "DISK usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE \"path\"='/' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "SEND NETWORK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE \"interface\"='eth0' AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "RCVD NETWORK",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s) FROM \"net\" WHERE \"interface\"='wlan0' AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "CPU idle time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"usage_idle\") FROM \"cpu\" WHERE \"cpu\"='cpu-total' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "MEMORY usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}